version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - warehouse_net

  app:
      build: .
      depends_on:
        - db
      environment:
        DATABASE_URL: postgres://postgres:postgres@db:5432/warehouse
      command: python main.py
